version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
    groups:
       discordjs:
          patterns:
            - "@discordjs/*"
            - "*discord*"
          update-types:
            - "minor"
            - "patch"
            - "major"
       dependencies:
          patterns:
            - "*" 
          update-types:
            - "minor"
            - "patch"
